# Generated by Django 4.2.7 on 2025-11-18 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Merchant business name', max_length=255)),
                ('business_registration_number', models.CharField(help_text='Unique business registration number', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Merchant contact email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Merchant contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='Pending', help_text='Current status of the merchant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='merchants_m_email_dab763_idx'), models.Index(fields=['business_registration_number'], name='merchants_m_busines_0ab132_idx'), models.Index(fields=['status'], name='merchants_m_status_128a55_idx')],
            },
        ),
    ]
